# Generated by Django 4.1.5 on 2023-01-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0002_remove_second_car_remove_second_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='second',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Груз'),
        ),
    ]
